# fly.toml app configuration file generated for my-own-ci-cd-pipeline on 2024-10-30T10:16:37-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-own-ci-cd-pipeline'
primary_region = 'qro'

[build]

[env]
  PORT = "3001" # add this where PORT matches the internal_port below

[processes]
  app = "node index.js" # add this

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
